# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EarningsNExpenses' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EarningsNExpenses
  
  pod 'Google/SignIn'
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'	
  
  

  target 'EarningsNExpensesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EarningsNExpensesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
